var_int=10
var_float=8.4
var_str="No"
big_int=var_int*3.5
var_float=var_float-1.0
print(big_int)
print(var_float)
print(var_int/var_float)
print(big_int/var_float)
var_str="No"*2+"YES"*3
print(var_str)
